{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: {{ .Values.namespace }}
  labels:
    app: birdseye-prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    rule_files:
      # - "first_rules.yml"
      # - "second_rules.yml"
    
    scrape_configs:
    - job_name: 'prometheus'
      static_configs:
      - targets: ['localhost:{{ .Values.prometheus.service.port }}']
    
    {{- if .Values.pushgateway.enabled }}
    - job_name: 'pushgateway'
      static_configs:
      - targets: ['birdseye-pushgateway-svc:{{ .Values.pushgateway.service.port }}']
      honor_labels: true
    {{- end }}
    
    {{- if .Values.frontend.enabled }}
    - job_name: 'birdseye-frontend'
      static_configs:
      - targets: ['birdseye-frontend-svc:{{ .Values.frontend.service.port }}']
      metrics_path: '/metrics'
      scrape_interval: 30s
    {{- end }}
    
    {{- if .Values.backend.enabled }}
    - job_name: 'birdseye-backend'
      static_configs:
      - targets: ['birdseye-backend-svc:{{ .Values.backend.service.port }}']
      metrics_path: '/metrics'
      scrape_interval: 30s
    {{- end }}
{{- end }}