version: '3.9'

services:
  frontend-dev:
    build:
      context: ../../
      dockerfile: .docker/dev/devfrontend.Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - type: bind
        source: ../../
        target: /workspace
        consistency: cached
    working_dir: /workspace
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: tail -f /dev/null
    depends_on:
      - backend-dev

  backend-dev:
    build:
      context: ../../
      dockerfile: .docker/dev/devbackend.Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - type: bind
        source: ../../
        target: /workspace
        consistency: cached
    working_dir: /workspace
    ports:
      - "8000:8000"
    environment:
      - PROMETHEUS_GATEWAY_URL=http://pushgateway:9091
      - FASTAPI_HOST=0.0.0.0
      - FASTAPI_PORT=8000
    command: tail -f /dev/null
    depends_on:
      - prometheus
      - pushgateway

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    depends_on:
      - pushgateway

  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway
    ports:
      - "9091:9091"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
