# monitoring/prometheus.yml

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'metrics_simulator_pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']
    scrape_interval: 15s
